import Head from 'next/head';

import Layout from '../components/Layout/Layout';
import PageTitle from '../components/Blogs/PageTitle/PageTitle';
import BlogsSection from '../components/Blogs/BlogsSection/BlogsSection';

import fs from 'fs';
import matter from 'gray-matter';

export default function Blogs({ blogs }) {
  // console.log(blogs);
  return (
    <>
      <Head>
        <title>IT Restaurant Blogs</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <PageTitle />
        <BlogsSection blogs={blogs} />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  // List of files in blogs folder
  const filesInBlogs = fs.readdirSync('./content/blogs');

  // Get the front matter and slug (the filename without .md) of all files
  const blogs = filesInBlogs.map((filename) => {
    const file = fs.readFileSync(`./content/blogs/${filename}`, 'utf8');
    const matterData = matter(file);

    return {
      ...matterData.data, // matterData.data contains front matter
      url: `/blogs/${filename.slice(0, filename.indexOf('.'))}`,
    };
  });

  return {
    props: {
      blogs,
    },
  };
}
