import Head from 'next/head';

import Layout from '../components/Layout/Layout';
import PageTitle from '../components/BlogSingle/PageTitle/PageTitle';
import BlogSingleSection from '../components/BlogSingle/BlogSingleSection/BlogSingleSection';
export default function ShopSingle() {
  return (
    <>
      <Head>
        <title>IT Restaurant Blog</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <PageTitle />
        <BlogSingleSection />
      </Layout>
    </>
  );
}
