import Head from 'next/head';

import Layout from '../components/Layout/Layout';
import PageTitle from '../components/Blog/PageTitle/PageTitle';
import BlogSection from '../components/Blog/BlogSection/BlogSection';

export default function Blog() {
  return (
    <>
      <Head>
        <title>IT Restaurant Blog</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <PageTitle />
        <BlogSection />
      </Layout>
    </>
  );
}
