import Head from 'next/head';

import Layout from '../components/Layout/Layout';
import SlideShow from '../components/Index/Slideshow/Slideshow';
import RestaurantDiscover from '../components/Index/RestaurantDiscover/RestaurantDiscover';
import OurBest from '../components/Index/OurBest/OurBest';
import OurServices from '../components/Index/OurServices/OurServices';
import OurDeliciousMenu from '../components/Index/OurDeliciousMenu/OurDeliciousMenu';
import OurSpecialDishes from '../components/Index/OurSpecialDishes/OurSpecialDishes';
import Carousel from '../components/Index/Carousel/Carousel';
import OurDelicious from '../components/Index/OurDelicious/OurDelicious';
import Testimonial from '../components/Index/Testimonial/Testimonial';
import OurBlog from '../components/Index/OurBlog/OurBlog';

export default function Index() {
  return (
    <>
      <Head>
        <title>IT Restaurant</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <SlideShow />
        <RestaurantDiscover />
        <OurBest />
        <OurServices />
        <OurDeliciousMenu />
        <OurSpecialDishes />
        <Carousel />
        <OurDelicious />
        <Testimonial />
        <OurBlog />
      </Layout>
    </>
  );
}
