import Head from 'next/head';
// import Image from 'next/image';
import { useEffect } from 'react';
import Layout from '../components/Layout/Layout';
import SlideShow from '../components/Index/Slideshow/Slideshow';
import RestaurantDiscover from '../components/Index/RestaurantDiscover/RestaurantDiscover';
import OurBest from '../components/Index/OurBest/OurBest';
import OurServices from '../components/Index/OurServices/OurServices';
import OurDeliciousMenu from '../components/Index/OurDeliciousMenu/OurDeliciousMenu';
import OurSpecialDishes from '../components/Index/OurSpecialDishes/OurSpecialDishes';
import Carousel from '../components/Index/Carousel/Carousel';
import OurDelicious from '../components/Index/OurDelicious/OurDelicious';
import Testimonial from '../components/Index/Testimonial/Testimonial';
import OurBlog from '../components/Index/OurBlog/OurBlog';
import ScrollUpButton from '../components/ScrollUpButton/ScrollUpButton';

import { fadeIn, fadeInRight, fadeInLeft, zoomIn } from 'react-animations';
import { StyleSheet, css } from 'aphrodite';

const classes = StyleSheet.create({
  fadeIn: {
    animationName: fadeIn,
    animationDuration: '1s',
  },
  fadeInRight: {
    animationName: fadeInRight,
    animationDuration: '1s',
  },
  fadeInLeft: {
    animationName: fadeInLeft,
    animationDuration: '1s',
  },
  zoomIn: {
    animationName: zoomIn,
    animationDuration: '1s',
  },
});

const animationList = ['fadeIn', 'fadeInRight', 'fadeInLeft', 'zoomIn'];

export default function Home() {
  const customAnimations = (classList) => {
    for (let i = 0; i < animationList.length; i++) {
      if (classList.contains(animationList[i])) {
        return animationList[i];
      }
    }

    return 'fadeIn';
  };
  useEffect(() => {
    let observer = new IntersectionObserver(
      (entries, observer) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            if (entry.target.classList.contains('animate')) {
              entry.target.style.visibility = 'visible';
              // entry.target.style.display = 'block';
              entry.target.classList.add(
                css(classes[customAnimations(entry.target.classList)])
              );
            }
            observer.unobserve(entry.target);
          }
        });
      },
      {
        threshold: 0.1,
      }
    );

    document.querySelectorAll('div').forEach((div) => {
      observer.observe(div);
    });
  });

  // useEffect(() => {
  //   window.onscroll = () => {
  //     if (window.pageYOffset === 0) {
  //       setTopCheck(true);
  //     } else {
  //       setTopCheck(false);
  //     }
  //   };
  // }, []);
  return (
    <>
      <Head>
        <title>IT Restaurant</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <SlideShow />
        <RestaurantDiscover />
        <OurBest />
        <OurServices />
        <OurDeliciousMenu />
        <OurSpecialDishes />
        <Carousel />
        <OurDelicious />
        <Testimonial />
        <OurBlog />
        <ScrollUpButton />
      </Layout>
    </>
  );
}
