import Head from 'next/head';

import Layout from '../components/Layout/Layout';
import OurDeliciousCombo from '../components/MenuSpecial/OurDeliciousCombo/OurDeliciousCombo';

export default function MenuSpecial() {
  return (
    <>
      <Head>
        <title>IT Restaurant Menu</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <OurDeliciousCombo />
      </Layout>
    </>
  );
}
